<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>MyBrowser.Driver.Legacy</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\MyBrowser.Abstractions\MyBrowser.Abstractions.csproj" />
    </ItemGroup>
</Project>